apiVersion: v1
kind: Service
metadata:
  name: django-app
  namespace: django-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: django-app
  type: ClusterIP