apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: django-app
spec:
  releaseName: nginx-ingress-controller
  chart:
    repository: nginx-stable
    name: nginx-ingress
    version: 1.41.3
  values:
    controller:
      service:
        type: LoadBalancer