# yaml file for helm release for nginx ingress controller
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: default
spec:
  releaseName: nginx-ingress
  chart:
    spec:
      chart: nginx-ingress
      version: 1.41.3
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: default
      interval: 1m
  interval: 1m