apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx
  namespace: django-app
spec:
  type: oci
  interval: 1m
  url: oci://registry-1.docker.io/bitnamicharts/nginx