apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress
      version: 3.30.0
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
  values:
    